// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LotId         string                 `protobuf:"bytes,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	PeerId        string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	T             int64                  `protobuf:"varint,4,opt,name=t,proto3" json:"t,omitempty"`
	R             int64                  `protobuf:"varint,5,opt,name=r,proto3" json:"r,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastEpoch     int64                  `protobuf:"varint,7,opt,name=last_epoch,json=lastEpoch,proto3" json:"last_epoch,omitempty"`
	LastTopTick   int64                  `protobuf:"varint,8,opt,name=last_top_tick,json=lastTopTick,proto3" json:"last_top_tick,omitempty"`
	IsBot         bool                   `protobuf:"varint,9,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	License       []byte                 `protobuf:"bytes,10,opt,name=license,proto3" json:"license,omitempty"`
	MsgSig        []byte                 `protobuf:"bytes,11,opt,name=msg_sig,json=msgSig,proto3" json:"msg_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *NodeMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeMessage) GetLotId() string {
	if x != nil {
		return x.LotId
	}
	return ""
}

func (x *NodeMessage) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *NodeMessage) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *NodeMessage) GetR() int64 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *NodeMessage) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *NodeMessage) GetLastEpoch() int64 {
	if x != nil {
		return x.LastEpoch
	}
	return 0
}

func (x *NodeMessage) GetLastTopTick() int64 {
	if x != nil {
		return x.LastTopTick
	}
	return 0
}

func (x *NodeMessage) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *NodeMessage) GetLicense() []byte {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *NodeMessage) GetMsgSig() []byte {
	if x != nil {
		return x.MsgSig
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"\x97\x02\n" +
	"\vNodeMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x15\n" +
	"\x06lot_id\x18\x02 \x01(\tR\x05lotId\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\x12\f\n" +
	"\x01t\x18\x04 \x01(\x03R\x01t\x12\f\n" +
	"\x01r\x18\x05 \x01(\x03R\x01r\x12\x1b\n" +
	"\tjoined_at\x18\x06 \x01(\x03R\bjoinedAt\x12\x1d\n" +
	"\n" +
	"last_epoch\x18\a \x01(\x03R\tlastEpoch\x12\"\n" +
	"\rlast_top_tick\x18\b \x01(\x03R\vlastTopTick\x12\x15\n" +
	"\x06is_bot\x18\t \x01(\bR\x05isBot\x12\x18\n" +
	"\alicense\x18\n" +
	" \x01(\fR\alicense\x12\x17\n" +
	"\amsg_sig\x18\v \x01(\fR\x06msgSigB\x06Z\x04./pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(*NodeMessage)(nil), // 0: message.NodeMessage
}
var file_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
